(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='devil-salon-campaign-v2';let saved=null,storageOK=true;try{saved=JSON.parse(localStorage.getItem(KEY)||'null');}catch{storageOK=false;}
const campaign=new SalonEngine.Campaign(saved),game=new SalonEngine.Game(Math.random,campaign),sound=new SalonSound(saved?.sound!==false);
let last=performance.now(),mode='start',pointer=null,resultAt=0,nextSnip=0,nextParticle=0,momentUntil=0,lastView='',mapReturn='start';const overlay=$('overlay'),main=document.querySelector('main'),stage=$('stage');
function save(){try{localStorage.setItem(KEY,JSON.stringify({...campaign.serialize(),sound:sound.enabled}));storageOK=true;}catch{storageOK=false;} $('save-note').textContent=storageOK?'进度自动保存在这台设备':'当前无法保存，关闭页面后进度可能丢失';}
function soundButton(){$('sound').textContent=sound.enabled?'♫':'♪';$('sound').setAttribute('aria-label',sound.enabled?'关闭音效':'开启音效');$('sound').setAttribute('aria-pressed',String(sound.enabled));}
function modal(next,title,copy,primary,symbol='✂',secondary='关卡手册'){mode=next;$('modal-title').textContent=title;$('modal-copy').textContent=copy;$('primary').textContent=primary;$('primary').hidden=false;$('modal-symbol').textContent=symbol;$('secondary').hidden=!secondary;$('secondary').textContent=secondary;$('level-grid').hidden=true;overlay.hidden=false;document.querySelector('.modal').classList.remove('map-modal');$('hold').disabled=true;$('primary').focus();}
function close(){overlay.hidden=true;$('hold').disabled=game.state!=='playing';last=performance.now();$('hold').focus({preventScroll:true});}
function start(index){if(!game.reset(index))return false;pointer=null;resultAt=0;momentUntil=0;$('moment').textContent='';sound.stop();sound.unlock();close();render();return true;}
function showStart(){const next=campaign.unlocked-1;modal('start',campaign.records.every(Boolean)?'十二关，全都拿下！':'今天，偷偷叛逆一下',`已解锁 ${campaign.unlocked} / 12 关。她分心时长按，黄色预警出现马上松手。`,`挑战第 ${String(next+1).padStart(2,'0')} 关`);}
function showMap(){mapReturn=mode;game.pause();pointer=null;sound.stop();modal('map','恶魔的关卡手册','通关前一关，才能解锁下一关。','返回','✦','');$('primary').hidden=true;$('level-grid').hidden=false;document.querySelector('.modal').classList.add('map-modal');const grid=$('level-grid');grid.replaceChildren();for(const c of campaign.cards()){const b=document.createElement('button');b.className='level-card'+(c.current?' current':'')+(c.stars?' complete':'');b.disabled=c.locked;b.setAttribute('aria-label',`第${c.index+1}关 ${c.name} ${c.locked?'未解锁':c.stars+'星'}`);const number=document.createElement('strong');number.textContent=c.locked?'锁定':c.number;const name=document.createElement('span');name.textContent=c.name;const status=document.createElement('small');status.textContent=c.locked?'先完成第'+c.index+'关':c.starText||'可挑战';b.append(number,name,status);b.onclick=()=>start(c.index);grid.append(b);}const back=document.createElement('button');back.className='secondary map-back';back.textContent=game.state==='paused'?'返回本局':'返回';back.onclick=()=>{if(game.state==='paused'){game.resume();close();render();}else showStart();};grid.append(back);grid.querySelector('button:not(:disabled)')?.focus();}
function moment(text){$('moment').textContent=text;momentUntil=performance.now()+1000;$('moment').classList.remove('pop');void $('moment').offsetWidth;$('moment').classList.add('pop');}
function particle(burst=false){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const count=burst?18:2;for(let i=0;i<count;i++){if($('particles').children.length>36)break;const p=document.createElement('span');p.className=burst?'confetti':'spark';p.textContent=i%3===0?'✦':'·';p.style.setProperty('--dx',(Math.random()*200-100)+'px');p.style.setProperty('--dy',(-40-Math.random()*110)+'px');p.style.setProperty('--rot',(Math.random()*360)+'deg');p.style.left=(burst?15+Math.random()*70:43+Math.random()*14)+'%';p.style.top=(burst?25:42)+'%';p.style.color=['#ffd68f','#fba9d0','#b9e9f8'][i%3];$('particles').append(p);setTimeout(()=>p.remove(),1100);}}
function event(e,now){if(e.type==='countdown')sound.play(e.value?'start':'go');if(e.type==='phase'){if(e.phase==='away'){sound.play(e.distraction==='drink'?'sip':e.distraction==='book'?'page':'ring');moment('机会来了！');}if(e.phase==='warning'){sound.play('warning');moment('快松手！');}}if(e.type==='dodge'){sound.play('dodge');moment('漂亮！极限收手');}if(e.type==='hair'){sound.play('magic');particle(true);moment('发型升级！');}if(e.type==='heartbeat')sound.play('heartbeat');if(e.type==='won'||e.type==='lost'){sound.stop();sound.play(e.type==='won'?'win':'lose');pointer=null;if(e.type==='won'){save();particle(true);moment('恶作剧成功！');}else moment(e.reason==='caught'?'被发现了！':'时间到！');resultAt=now+850;}}
function render(){const now=performance.now();for(const e of game.takeEvents())event(e,now);const s=game.snapshot(),visual=SalonPresentation.frame(s);$('level').textContent=`${String(s.level+1).padStart(2,'0')} / ${s.name}`;$('chapter').textContent=s.chapter;$('time').textContent=`◷ ${s.remaining}s`;$('time').classList.toggle('urgent',s.remaining<=10);$('percent').innerHTML=s.percent+'<span>%</span>';$('fill').style.width=s.progress+'%';document.querySelector('.track').setAttribute('aria-valuenow',s.percent);
const view=`stage ${s.phase} ${s.holding?'cutting':''} ${s.state} ${s.remaining<=10?'urgent':''}`;if(view!==lastView){stage.className=view;lastView=view;}$('status').className='status '+s.phase;const status=s.state==='countdown'?'准备好，看准时机':s.state==='ready'?'趁她分心，偷偷换个发型':s.title;if($('status-text').textContent!==status)$('status-text').textContent=status;$('status-icon').textContent=s.phase==='away'?'✦':s.phase==='warning'?'!':'◉';$('bubble').textContent=visual.bubble;document.querySelector('.devil').style.backgroundPosition=visual.devilX+'% '+visual.devilY+'%';document.querySelector('.angel').style.backgroundPosition=visual.angelX+'% '+visual.angelY+'%';$('guest-before').style.backgroundPosition=visual.guestX+'% '+visual.guestY+'%';$('guest-after').style.backgroundPosition=visual.afterX+'% '+visual.guestY+'%';$('guest-after').style.opacity=visual.makeover;$('guest-name').textContent=visual.guestName+' · 第 '+(s.level+1)+' 位客人';stage.style.setProperty('--cut-speed',Math.max(.12,.28-s.boost*.004)+'s');$('hold').classList.toggle('pressed',s.holding);$('hold-label').textContent=s.holding?'嘘…正在偷偷剪':'长按 · 偷偷剪';$('hold').disabled=s.state!=='playing'||!overlay.hidden;$('pause').disabled=!['playing','countdown'].includes(s.state);$('warning-fill').style.transform=`scaleX(${Math.min(1,s.warningFraction)})`;$('combo').hidden=!s.holding||s.combo<2;$('combo').textContent=`连剪 ${s.combo} ✂  +${s.boost}%`;$('count-in').hidden=s.state!=='countdown';$('count-in').textContent=s.countdown||'GO';if(now>momentUntil)$('moment').textContent='';if(s.holding&&s.state==='playing'){if(now>=nextSnip){sound.play('snip');nextSnip=now+Math.max(115,210-s.boost*2);}if(now>=nextParticle){particle();nextParticle=now+150;}}if(resultAt&&now>=resultAt&&overlay.hidden){resultAt=0;if(s.state==='won'){const last=s.level===11;modal('won',last?'首席恶魔，正式毕业！':'这一剪，漂亮！',`第 ${s.level+1} 关完成 · 剩余 ${s.remaining} 秒\n${'★'.repeat(s.stars)}${'☆'.repeat(3-s.stars)}${last?'':'\n第 '+(s.level+2)+' 关已解锁'}`,last?'再挑战这一关':'挑战下一关','✦');}else modal('lost',s.reason==='caught'?'哎呀，被抓包了！':'差一点就成功了',s.reason==='caught'?'黄色预警时马上松手，店长回头就安全了。':'多抓住几次分心的机会，再来一局。','重试这一关','!');}}
function release(e){if(e&&pointer!==null&&e.pointerId!==undefined&&e.pointerId!==pointer)return;pointer=null;game.release();render();}
$('hold').addEventListener('pointerdown',e=>{if(pointer!==null||e.button>0||!overlay.hidden||game.state!=='playing')return;e.preventDefault();sound.unlock();pointer=e.pointerId;$('hold').setPointerCapture(e.pointerId);game.press();render();});for(const t of ['pointerup','pointercancel','lostpointercapture'])$('hold').addEventListener(t,release);window.addEventListener('pointerup',release);$('hold').addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{if(e.code==='Space'&&overlay.hidden&&e.target===$('hold')){e.preventDefault();if(!e.repeat){sound.unlock();game.press();render();}}if(e.key==='Escape'&&overlay.hidden)pause();if(e.key==='Tab'&&!overlay.hidden){const nodes=[...overlay.querySelectorAll('button:not(:disabled)')].filter(el=>!el.hidden&&el.getClientRects().length);const first=nodes[0],end=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();end?.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first?.focus();}}});window.addEventListener('keyup',e=>{if(e.code==='Space')release();});
$('primary').onclick=()=>{sound.unlock();if(mode==='start')start(campaign.unlocked-1);else if(mode==='won')start(Math.min(11,game.level+1));else if(mode==='lost')start(game.level);else{if(game.state==='paused'){game.resume();close();render();}else showStart();}};$('secondary').onclick=showMap;$('map').onclick=showMap;
function pause(){game.pause();pointer=null;sound.stop();if(game.state==='paused'){modal('pause','休息一下','剪刀和倒计时都暂停了。','继续游戏','Ⅱ');render();}}$('pause').onclick=pause;document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',()=>{if(['playing','countdown'].includes(game.state))pause();});
$('help').onclick=()=>{game.pause();pointer=null;sound.stop();modal('help','偷剪四步曲','① 她盯着顾客：等待。\n② 她接电话：长按，连剪会加速。\n③ 黄色预警：立刻松手。\n④ 填满进度：过关并解锁下一关。','知道了','?','');};$('install').onclick=()=>{game.pause();pointer=null;sound.stop();modal('install','放到 iPhone 主屏幕','用 Safari 打开游戏链接，点击分享，再选择「添加到主屏幕」。\n解锁记录只保存在当前浏览器或主屏幕应用中。','知道了','↗','');};$('sound').onclick=()=>{sound.setEnabled(!sound.enabled);soundButton();save();if(sound.enabled)sound.play('go');};
function frame(now){game.tick((now-last)/1000);last=now;render();requestAnimationFrame(frame);}soundButton();$('save-note').textContent=storageOK?'进度自动保存在这台设备':'旧进度读取失败，本次从第1关开始';showStart();render();requestAnimationFrame(frame);
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'read_game_state',description:'Read level, progress and unlocked stages.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw Error('No parameters expected');return game.snapshot();}},{name:'start_unlocked_level',description:'Start a selected unlocked level with the same countdown as the level picker. Locked levels cannot be started.',inputSchema:{type:'object',properties:{level:{type:'integer',minimum:1,maximum:12}},required:['level'],additionalProperties:false},execute(input){if(!input||Object.keys(input).length!==1||!Number.isInteger(input.level)||!campaign.canPlay(input.level-1))throw Error('Level is invalid or locked');start(input.level-1);return game.snapshot();}},{name:'pause_game',description:'Pause the visible round and release the scissors.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute(input){if(input&&Object.keys(input).length)throw Error('No parameters expected');pause();return game.snapshot();}}])try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
})();
